name: Deploy to S3
on:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          VITE_BACKEND_URL: ${{ vars.BACKEND_URL }}
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
          retention-days: 1
  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.caas.sn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy
        uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: --acl public-read --follow-symlinks --delete
          folder: dist
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'